---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cloudflared-config
data:
  config.yaml: |
    metrics: 0.0.0.0:2000
    no-autoupdate: true
    ingress:
    - hostname: {{ .Values.tunnel.hostname }}
      service: http://printer-service:3000  # Changed from {{ .Release.Name }}-service
    - service: http_status:404