# templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-alexprinter
spec:
  selector:
    matchLabels:
      app: alexprinter
  template:
    metadata:
      labels:
        app: alexprinter
    spec:
      containers:
      - name: alexprinter
        image: "{{ .Values.alexPrinter.image.repository }}:{{ .Values.alexPrinter.image.tag }}"
        imagePullPolicy: {{ .Values.alexPrinter.image.pullPolicy }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: "{{ .Values.cloudflared.image.repository }}:{{ .Values.cloudflared.image.tag }}"
        imagePullPolicy: {{ .Values.cloudflared.image.pullPolicy }}
        args:
        - "tunnel"
        - "--no-autoupdate"
        - "run"
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.cloudflared.tunnel.existingSecret }}
              key: {{ .Values.cloudflared.tunnel.tokenKey }}