---
# templates/deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-tunnel
spec:
  replicas: {{ .Values.cloudflared.replicas | default 1 }}
  selector:
    matchLabels:
      app: cloudflared-tunnel
  template:
    metadata:
      labels:
        app: cloudflared-tunnel
    spec:
      containers:
        - name: cloudflared-tunnel
          image: {{ .Values.cloudflared.image | default "cloudflare/cloudflared:latest" }}
          command: ["sh", "-c", "{{ .Values.cloudflared.command | default "tunnel --no-autoupdate run" }}"]
          {{- if .Values.cloudflared.env }}
          env:
            {{- range .Values.cloudflared.env }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: {{ .valueFrom.secretKeyRef.name }}
                  key: {{ .valueFrom.secretKeyRef.key }}
            {{- end }}
          {{- end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alexprinter
spec:
  replicas: {{ .Values.alexprinter.replicas | default 1 }}
  selector:
    matchLabels:
      app: alexprinter
  template:
    metadata:
      labels:
        app: alexprinter
    spec:
      containers:
        - name: alexprinter
          image: {{ .Values.alexprinter.image | default "bmo75/alex-printer-build-counter:latest" }}
